### PR TITLE
chore: structuring third-party tests

### PR DESCRIPTION
**Pull request by KennedyTedesco**
This PR only touches the third-party tests implementing a `Repository` struct but keeping the behavior.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@KennedyTedesco Happy New Year! What is the overall improvement provided by this PR?

**Comment by KennedyTedesco** [comment]
Happy new year! (almost there in my TZ, UTC -3 lol) :partying_face:  Let 2023 be the start of something great for all of us!

The current code is structured in a single function doing everything, while the new one uses a struct definition along with some methods to orchestrate the steps needed to get the entries: 

1) create_output_dir() 
2) clone_repository() 
3) install_composer() 
4) and finally, returns the entries via read_directory()

I think the new version makes things a bit more sane to read and mantain.

But this code does not fix anything new. It is more aesthetics than anything. So, it is understandable if you don't want to mess with this part. Always feel free to close. Your judgment is way better than mine since I am still very beginner at the project. :v:

**Comment by ryangjchandler** [comment]
I like the general idea behind the changes but I'm happy with how it's all working right now. The code inside of the test utilities is rarely touched and does everything we need it to do for now so I'm going to close this one.

**Comment by KennedyTedesco** [comment]
Fair enough! 👍

**Pull request closed without merging**
