### PR TITLE
add-chubbyphp-framework

### PR DESCRIPTION
**Pull request by dominikzogg**
@azjezz PR based on your link within the tweet https://twitter.com/azjezz/status/1600960177179873280. Hopefully I have done this correctly

### CODE REVIEW

**Review by azjezz — APPROVED** [review]

**Comment by dominikzogg** [comment]
@azjezz i see my mistake, will fix it

**Review by azjezz — APPROVED** [review]

**Comment by dominikzogg** [comment]
@azjezz you were faster in approving the pr again, that i open the tab in my browser ;-)

**Comment by azjezz** [comment]
Thanks @dominikzogg!

**Comment by dominikzogg** [comment]
@azjezz thanks for merging

**Pull request merged**
